#include "Config.hpp"
#include <fstream>
#include <sstream>
#include <algorithm>
#include <filesystem>
#include <iostream>
#include <iomanip>
#include <variant>
#include <nlohmann/json.hpp>

namespace nlm {

struct Config::Impl {
    std::vector<ConfigEntry> entries;
};

Config::Config() : pImpl(std::make_unique<Impl>()) {}

Config::~Config() = default;

Config::Config(Config&&) noexcept = default;

Config& Config::operator=(Config&&) noexcept = default;

bool Config::loadFromFile(const std::string& filepath) {
    std::ifstream file(filepath);
    if (!file.is_open()) {
        std::cerr << "Error: Cannot open config file: " << filepath << std::endl;
        return false;
    }
    
    std::string line;
    int lineNum = 0;
    while (std::getline(file, line)) {
        ++lineNum;
        // Skip comments and empty lines
        line = trim(line);
        if (line.empty() || line[0] == '#' || line[0] == '/') {
            continue;
        }
        
        // Parse key=value pairs
        size_t pos = line.find('=');
        if (pos == std::string::npos) {
            std::cerr << "Warning: Invalid config line " << lineNum << " (no '='): " << line << std::endl;
            continue;
        }
        
        std::string key = trim(line.substr(0, pos));
        std::string value = trim(line.substr(pos + 1));
        
        // Remove quotes if present
        if (value.size() >= 2 && 
            ((value.front() == '"' && value.back() == '"') ||
             (value.front() == '\'' && value.back() == '\''))) {
            value = value.substr(1, value.size() - 2);
        }
        
        set(key, value, ConfigSource::File);
    }
    
    return true;
}

bool Config::loadFromArgs(int argc, char** argv) {
    for (int i = 1; i < argc; ++i) {
        std::string arg(argv[i]);
        
        if (arg.substr(0, 2) == "--") {
            size_t pos = arg.find('=');
            if (pos != std::string::npos) {
                std::string key = arg.substr(2, pos - 2);
                std::string value = arg.substr(pos + 1);
                set(key, value, ConfigSource::CommandLine);
            }
        } else if (arg[0] == '-' && i + 1 < argc) {
            std::string key = arg.substr(1);
            std::string value = argv[++i];
            set(key, value, ConfigSource::CommandLine);
        }
    }
    return true;
}

bool Config::saveToFile(const std::string& filepath) const {
    std::ofstream file(filepath);
    if (!file.is_open()) {
        std::cerr << "Error: Cannot save config to file: " << filepath << std::endl;
        return false;
    }
    
    file << "# NLM Configuration File\n";
    file << "# Generated by NLM on " << __DATE__ << " at " << __TIME__ << "\n\n";
    
    for (const auto& entry : pImpl->entries) {
        file << "# " << entry.description << "\n";
        file << entry.key << " = ";
        
        std::visit([&file](auto&& arg) {
            using T = std::decay_t<decltype(arg)>;
            if constexpr (std::is_same_v<T, int>) {
                file << arg;
            } else if constexpr (std::is_same_v<T, int64_t>) {
                file << arg;
            } else if constexpr (std::is_same_v<T, double>) {
                file << std::fixed << std::setprecision(6) << arg;
            } else if constexpr (std::is_same_v<T, bool>) {
                file << (arg ? "true" : "false");
            } else if constexpr (std::is_same_v<T, std::string>) {
                file << "\"" << arg << "\"";
            } else if constexpr (std::is_same_v<T, std::vector<int>>) {
                file << "[";
                bool first = true;
                for (const auto& item : arg) {
                    if (!first) file << ", ";
                    file << item;
                    first = false;
                }
                file << "]";
            } else if constexpr (std::is_same_v<T, std::vector<double>>) {
                file << "[";
                bool first = true;
                for (const auto& item : arg) {
                    if (!first) file << ", ";
                    file << std::fixed << std::setprecision(6) << item;
                    first = false;
                }
                file << "]";
            } else if constexpr (std::is_same_v<T, std::vector<std::string>>) {
                file << "[";
                bool first = true;
                for (const auto& item : arg) {
                    if (!first) file << ", ";
                    file << "\"" << item << "\"";
                    first = false;
                }
                file << "]";
            } else {
                file << "UNKNOWN_TYPE";
            }
        }, entry.value);
        
        file << "\n\n";
    }
    
    return true;
}

bool Config::exportToJson(const std::string& filepath) const {
    nlohmann::json j = nlohmann::json::object();
    
    for (const auto& entry : pImpl->entries) {
        nlohmann::json entryObj = nlohmann::json::object();
        entryObj["value"] = serializeConfigValue(entry.value);
        entryObj["source"] = static_cast<int>(entry.source);
        entryObj["description"] = entry.description;
        
        j[entry.key] = entryObj;
    }
    
    std::ofstream file(filepath);
    if (!file.is_open()) {
        std::cerr << "Error: Cannot write JSON config to file: " << filepath << std::endl;
        return false;
    }
    
    file << std::setw(2) << j << std::endl;
    return true;
}

// Static helper function for JSON serialization
nlohmann::json serializeConfigValue(const ConfigValue& value) {
    return std::visit([](auto&& arg) -> nlohmann::json {
        using T = std::decay_t<decltype(arg)>;
        if constexpr (std::is_same_v<T, int>) {
            return arg;
        } else if constexpr (std::is_same_v<T, int64_t>) {
            return arg;
        } else if constexpr (std::is_same_v<T, double>) {
            return arg;
        } else if constexpr (std::is_same_v<T, bool>) {
            return arg;
        } else if constexpr (std::is_same_v<T, std::string>) {
            return arg;
        } else if constexpr (std::is_same_v<T, std::vector<int>>) {
            nlohmann::json j = nlohmann::json::array();
            for (const auto& item : arg) {
                j.push_back(item);
            }
            return j;
        } else if constexpr (std::is_same_v<T, std::vector<double>>) {
            nlohmann::json j = nlohmann::json::array();
            for (const auto& item : arg) {
                j.push_back(item);
            }
            return j;
        } else if constexpr (std::is_same_v<T, std::vector<std::string>>) {
            nlohmann::json j = nlohmann::json::array();
            for (const auto& item : arg) {
                j.push_back(item);
            }
            return j;
        } else {
            return nullptr;
        }
    }, value);
}

// Template function implementations
template<typename T>
std::optional<T> Config::get(const std::string& key) const {
    auto it = std::find_if(pImpl->entries.begin(), pImpl->entries.end(),
        [&key](const ConfigEntry& e) { return e.key == key; });
    
    if (it == pImpl->entries.end()) {
        return std::nullopt;
    }
    
    try {
        return std::get<T>(it->value);
    } catch (const std::bad_variant_access&) {
        return std::nullopt;
    }
}

// Template function implementations
template<typename T>
T Config::getOr(const std::string& key, const T& defaultValue) const {
    auto val = get<T>(key);
    return val.has_value() ? val.value() : defaultValue;
}

// Set with type conversion and validation
template<typename T>
void Config::set(const std::string& key, T value, ConfigSource source) {
    // Basic type validation
    if constexpr (std::is_same_v<T, std::string>) {
        if (value.empty()) {
            std::cerr << "Warning: Empty value for config key: " << key << std::endl;
        }
    } else if constexpr (std::is_same_v<T, int> || std::is_same_v<T, int64_t>) {
        if (value == 0) {
            std::cerr << "Warning: Zero value for config key: " << key << std::endl;
        }
    } else if constexpr (std::is_same_v<T, double>) {
        if (value == 0.0) {
            std::cerr << "Warning: Zero value for config key: " << key << std::endl;
        }
    } else if constexpr (std::is_same_v<T, bool>) {
        // No validation needed for bool
    }
    
    set(key, ConfigValue(value), source);
}

// Convenience overloads for common types
void Config::set(const std::string& key, const std::string& value, ConfigSource source) {
    set<std::string>(key, value, source);
}

void Config::set(const std::string& key, int value, ConfigSource source) {
    set<int>(key, value, source);
}

void Config::set(const std::string& key, double value, ConfigSource source) {
    set<double>(key, value, source);
}

void Config::set(const std::string& key, bool value, ConfigSource source) {
    set<bool>(key, value, source);
}

bool Config::has(const std::string& key) const {
    return std::any_of(pImpl->entries.begin(), pImpl->entries.end(),
        [&key](const ConfigEntry& e) { return e.key == key; });
}

void Config::remove(const std::string& key) {
    pImpl->entries.erase(
        std::remove_if(pImpl->entries.begin(), pImpl->entries.end(),
            [&key](const ConfigEntry& e) { return e.key == key; }),
        pImpl->entries.end()
    );
}

std::vector<std::string> Config::getKeys() const {
    std::vector<std::string> keys;
    keys.reserve(pImpl->entries.size());
    for (const auto& entry : pImpl->entries) {
        keys.push_back(entry.key);
    }
    return keys;
}

void Config::clear() {
    pImpl->entries.clear();
}

std::string Config::summary() const {
    std::ostringstream oss;
    oss << "Configuration (" << pImpl->entries.size() << " entries):\n";
    for (const auto& entry : pImpl->entries) {
        oss << "  " << entry.key << " = [";
        std::visit([&oss](auto&& arg) {
            using T = std::decay_t<decltype(arg)>;
            if constexpr (std::is_same_v<T, std::string>) {
                oss << "\"" << arg << "\"";
            } else if constexpr (std::is_same_v<T, bool>) {
                oss << (arg ? "true" : "false");
            } else {
                oss << arg;
            }
        }, entry.value);
        oss << "] (" << static_cast<int>(entry.source) << ")\n";
    }
    return oss.str();
}

std::string Config::trim(const std::string& str) {
    size_t start = str.find_first_not_of(" \t\r\n");
    if (start == std::string::npos) return "";
    size_t end = str.find_last_not_of(" \t\r\n");
    return str.substr(start, end - start + 1);
}

std::string Config::toLower(const std::string& str) {
    std::string result = str;
    std::transform(result.begin(), result.end(), result.begin(), ::tolower);
    return result;
}

// Explicit template instantiations
template std::optional<int> Config::get<int>(const std::string&) const;
template std::optional<int64_t> Config::get<int64_t>(const std::string&) const;
template std::optional<double> Config::get<double>(const std::string&) const;
template std::optional<bool> Config::get<bool>(const std::string&) const;
template std::optional<std::string> Config::get<std::string>(const std::string&) const;

template int Config::getOr<int>(const std::string&, const int&) const;
template int64_t Config::getOr<int64_t>(const std::string&, const int64_t&) const;
template double Config::getOr<double>(const std::string&, const double&) const;
template bool Config::getOr<bool>(const std::string&, const bool&) const;
template std::string Config::getOr<std::string>(const std::string&, const std::string&) const;

} // namespace nlm

// External function implementations for JSON serialization
nlohmann::json serializeConfigValue(const ConfigValue& value) {
    return nlm::serializeConfigValue(value);
}